function stereoParams = calibrate(imageFileNamesLeft, imageFileNamesRight)
    % imageFileNamesLeft = {'/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0002.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0003.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0005.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0006.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0007.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0008.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0010.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0011.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0012.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/color/color0013.jpg',...
    %     };
    % imageFileNamesRight = {'/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0002.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0003.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0005.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0006.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0007.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0008.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0010.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0011.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0012.jpg',...
    %     '/Users/danielsuo/mobot/src/capture/calibration/iPod/infrared/infrared0013.jpg',...
    %     };

    % Detect checkerboards in images
    [imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNamesLeft, imageFileNamesRight);

    % Generate world coordinates of the checkerboard keypoints
    squareSize = 30;  % in units of 'mm'
    worldPoints = generateCheckerboardPoints(boardSize, squareSize);

    % Calibrate the camera
    [stereoParams, pairsUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
        'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
        'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');
    
    % Save data
    KK_left = stereoParams.CameraParameters1.IntrinsicMatrix';
    KK_right = stereoParams.CameraParameters2.IntrinsicMatrix';

    R = stereoParams.RotationOfCamera2';
    T = stereoParams.TranslationOfCamera2';

    save('Calib_Results_stereo.mat', 'R', 'T', 'KK_left', 'KK_right');
end