#!/usr/bin/env bash

# $1: input dir
# $2: output dir

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

$DIR/copy_and_rename $1 $2 jpg jpg color%04d
$DIR/copy_and_rename $1 $2 png png infrared%04d

cd $2

# Trim infrared images to 640x480
mogrify -crop 640x480+0+4 *.png

# Convert format
mogrify -format jpg *.png

# Remove png
rm *png

# Put in correct folders
mkdir color
mv color*jpg color
mkdir infrared
mv infrared*jpg infrared