#!/usr/bin/env bash

# Ubuntu

# Install OS Mesa
sudo apt-get install -y libosmesa6 libosmesa6-dev libglu1-mesa libgflags-dev libgoogle-glog-dev liblmdb-dev libeigen3-dev

# Install CUDA
wget http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb
sudo apt-get update
sudo apt-get install cuda

