#!/bin/bash

# TODO: Need to update this for OS X and Linux; right now a mix of both...

# Install OS Mesa, Ceres, and libcurl
sudo apt-get install -y libosmesa6 libosmesa6-dev libglu1-mesa libgflags-dev libgoogle-glog-dev liblmdb-dev libeigen3-dev libsuitesparse-dev libatlas-base-dev libcurl4-openssl-dev clang

# Install CUDA
wget http://developer.download.nvidia.com/compute/cuda/7.5/Prod/local_installers/cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb
sudo dpkg -i cuda-repo-ubuntu1504-7-5-local_7.5-18_amd64.deb
sudo apt-get update
sudo apt-get install cuda

# Install CERES
brew install cmake glog eigen suite-sparse
git clone https://ceres-solver.googlesource.com/ceres-solver vendor/ceres-solver
cd vendor/ceres-solver
mkdir build
cd build
cmake ..
make -j3
make test
make install
cd ../../../

# Make
mkdir build && cd build
cmake ..
make

# Install dependencies for Facebook folly
sudo apt-get install -y \
    g++ \
    automake \
    autoconf \
    autoconf-archive \
    libtool \
    libboost-all-dev \
    libevent-dev \
    libdouble-conversion-dev \
    libgoogle-glog-dev \
    libgflags-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    make \
    zlib1g-dev \
    binutils-dev \
    libjemalloc-dev \
    libssl-dev \
    libunwind8-dev \
    libelf-dev \
    libdwarf-dev \
    libiberty-dev

git clone https://github.com/facebook/folly vendor/folly

cd vendor/folly/folly

autoreconf -ivf
./configure
make
make check
sudo make install

cd ../../../

git clone https://github.com/facebook/wangle vendor/wangle

cd vendor/wangle/wangle

cmake .
make
ctest
sudo make install

cd ../../../

