#!/usr/bin/env bash

#############################################################################
# General installation
#############################################################################

# Install brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Update brew
brew update

# SERVER INSTALL
brew install node

# Install dependencies
npm install